/* Japanese: every text of the plugin (the table of re_lang.c has no Japanese column). Included by re_lang.c only.
 * The words are the game's own where it has one (modsLanguages/jp): 破産, 認知度, 資産, フロアスペース, 家具, 退職金,
 * 取締役会, ビジネス, 従業員, 候補者, 作業効率, 時給. Full-width letters are twice as wide: a line of a hover text
 * is at most about 17 of them. */
static const char *const LANG_JP[RE_MSG_COUNT] = {
    [RE_MSG_PER_LOSS] = "PER: 赤字",
    [RE_MSG_HOVER_YIELD] = "、配当 %.1f%%",
    [RE_MSG_HOVER_UNDER] = "PBR 0.75未満: ",
    [RE_MSG_HOVER_BANKRUPT] = "%s%s月末に破産%s",
    [RE_MSG_HOVER_MEASURE] = "%s%s月末に縮小または増資%s",
    [RE_MSG_HOVER_WATCH] = "%s%dか月以内: 株価が%.1f%%下がると破産%s",
    [RE_MSG_HOVER_NEAR] = "株価 -%.1f%%で月末に縮小・増資",
    [RE_MSG_HOVER_FAIR] = "適正 %s (%+.0f%%)",
    [RE_MSG_HOVER_TAILWIND] = "、業界好調",
    [RE_MSG_HOVER_HEADWIND] = "、業界不振",
    [RE_MSG_NO_FAIR] = "適正株価なし (自己資本が尽きた)",
    [RE_MSG_ROW_FAIR] = " (適正 %s)",
    [RE_MSG_ROW_BANKRUPT] = "月末に破産",
    [RE_MSG_ROW_MEASURE] = "月末に縮小・増資",
    [RE_MSG_ROW_PER_MONTH] = " (月 %s)",
    [RE_MSG_ROW_WATCH] = "破産注意",
    [RE_MSG_ROW_OF_EQUITY] = " (自己資本の%.1f%%)",
    [RE_MSG_ROW_OF_PRICE] = " (株価の%.1f%%)",
    [RE_MSG_IPO_REST] = "、残りは%sで売却",
    [RE_MSG_EDU_FIXED] = "年間の固定金利 (入学する月の中央銀行金利)",
    [RE_MSG_GRADE_QUOTE] = " (信用格付け %s、購入時に再計算)",
    [RE_MSG_GRADE] = " (信用格付け %s)",
    [RE_MSG_GRADE_PREFIX] = "信用格付け ",
    [RE_MSG_GRADE_CHANGE] = "信用格付け %s → %s",
    [RE_MSG_FORECAST_PREFIX] = "今月末: ",
    [RE_MSG_FORECAST_LOANS] = "%sローン返済 %s",
    [RE_MSG_FORECAST_CASH] = "%s必要な現金 %s",
    [RE_MSG_LOCK_PREFIX] = "取引ロック",
    [RE_MSG_LOCK_RUNS] = "取引ロック: あと",
    [RE_MSG_LOCK_RUNS_REST] = "%s%lld時間 (株式・先物)",
    [RE_MSG_LOCK_NONE] = "%s: なし",
    [RE_MSG_LOCK_OVER] = "%s解除",
    [RE_MSG_AUTO_PREFIX] = "自動振替:",
    [RE_MSG_AUTO_SKIPPED] = "%s 株式購入%d件をスキップ (取引ロック)",
    [RE_MSG_HELD_PREFIX] = "保有株式の警告: ",
    [RE_MSG_HELD_CLOSE] = "株価 -%.1f%%で月末に縮小・増資",
    [RE_MSG_HELD_WATCH] = "株価 -%.1f%%で月末に破産",
    [RE_MSG_HELD_MORE] = " ほか%d件",
    [RE_MSG_LOCK_REFUSED] = "取引ロック中: あと%lld時間は株式・先物の取引不可",
    [RE_MSG_CASINO_SLOTS] = "スロット",
    [RE_MSG_CASINO_ROULETTE] = "ルーレット",
    [RE_MSG_CASINO_BLACKJACK] = "ブラックジャック",
    [RE_MSG_CASINO_BACCARAT] = "バカラ",
    [RE_MSG_CASINO_WON] = "%s: 賭け金の%s倍を獲得 (+%s)",
    [RE_MSG_CASINO_LOST] = "%s: はずれ (-%s)",
    [RE_MSG_CASINO_PLAYED] = "%s: 今月はロード前にプレイ済み。今回は結果なし",
    [RE_MSG_CASINO_BEFORE] = "%s: MOD導入前に始めたゲーム。結果は開始時に確定済みで、これ以上の入出金はない",
    [RE_MSG_ADOPT_PREFIX] = "MOD導入前のセーブ: ",
    [RE_MSG_ADOPT] = "%sビジネス%d件の「古い資産の自動再購入」と従業員%d人の自動管理をオフにした。MODではどちらも働きが増えて"
                     "いるので、必要な所だけオンに戻すこと",
    [RE_MSG_ADOPT_ASSETS] = "%sビジネス%d件の「古い資産の自動再購入」をオフにした。MODではこのスイッチの働きが増えているので、"
                            "必要な所だけオンに戻すこと",
    [RE_MSG_ADOPT_STAFF] = "%s従業員%d人の自動管理をオフにした。MODではこのスイッチの働きが増えているので、必要な所だけオンに"
                           "戻すこと",
    [RE_MSG_ADOPT_CASINO] = "キューにあったカジノのアクション%d件を外した。MODでは賭け金を払い、結果は終了時に出る。必要なら"
                            "入れ直すこと",
    [RE_MSG_ADOPT_CASINO_BEGUN] = "キューにあったカジノのアクション%d件を外した。うち%d件は開始済みで、結果は開始時のまま、今月"
                                  "プレイ済みとして扱う。MODでは賭け金を払い、結果は終了時に出る。必要なら入れ直すこと",
    [RE_MSG_CASINO_BACK_PREFIX] = "カジノ: ",
    [RE_MSG_CASINO_BACK] = "%sロード前にプレイした%d件はそのまま有効 (現金 %s)",
    [RE_MSG_CASINO_TIP] = "月1回。当選 ",
    [RE_MSG_CASINO_TIP_PRIZE] = "%s%s%%: %s倍",
    [RE_MSG_STAFF_LINE] = "実効1時間あたり %s",
    [RE_MSG_HIRE_ORDER] = " (実効時給の安い順)",
    [RE_MSG_STAFF_TIP] = "実効1時間あたり %s (時給 ÷ 作業効率 %.0f%%)",
    [RE_MSG_OFFER_TIP] = "標準コスト比 %+.1f%%\n1時間あたり %s 残る",
    [RE_MSG_FUT_EXPECTED] = " (予想 %.2f%%)",
    [RE_MSG_FUT_TIP] = "予想: ゲームの規則どおりに動いた場合の、選んだ満期までの平均インフレ率。今の率より高ければ買い、"
                       "低ければ売りが有利。",
    [RE_MSG_FUT_ITEM] = " (年%+.1f%%)",
    [RE_MSG_FUT_ITEM_AHEAD] = " (%+.1f%% → %+.1f%%)",
    [RE_MSG_FUT_ROW_TIP] = "インフレ率 年%+.2f%%\n予想 6か月: %+.2f%%\n予想 12か月: %+.2f%%\n予想 24か月: %+.2f%%\n予想が高ければ"
                           "買い、低ければ売り",
    [RE_MSG_FUT_SORT] = "12か月予想 - 現在の率\n大きい順に並べる",
    [RE_MSG_CHART_HALF_YEAR] = "6か月",
    [RE_MSG_CHART_INDEX] = " (最初の月 = 100)",
    [RE_MSG_RESEARCH_PREFIX] = "株式調査の購読: ",
    [RE_MSG_RESEARCH_PAID] = "%s%d社を再調査、購読料 %s",
    [RE_MSG_RESEARCH_SHORT] = "%s%d社を再調査、購読料 %s。現金が足りず、%s が負債になった",
    [RE_MSG_RESEARCH_KEPT_PREFIX] = "支払い済みの調査購読料: ",
    [RE_MSG_RESEARCH_KEPT] = "%s前のセーブをロードしても戻らない。今月支払った%d社を再調査し、%s を再度支払った",
    [RE_MSG_RESEARCH_KEPT_SHORT] = "%s前のセーブをロードしても戻らない。今月支払った%d社を再調査し、%s を再度支払った。現金が"
                                   "足りず、%s が負債になった",
    [RE_MSG_RESEARCH_KEPT_TICK] = "ロード前に支払った調査購読料を再度支払った: %s (%d社)",
    [RE_MSG_RESEARCH_ONE_ON] = "調査購読: %s オン。今調査した、購読料 %s (毎月)",
    [RE_MSG_RESEARCH_ONE_OFF] = "調査購読: %s オフ。来月から料金なし",
    [RE_MSG_RESEARCH_ALL_ON] = "調査購読: 全社オン。%d社を今調査した、購読料 %s",
    [RE_MSG_RESEARCH_ALL_OFF] = "調査購読: すべてオフ。来月から料金なし",
    [RE_MSG_RESEARCH_ONE_ON_DONE] = "調査購読: %s オン。今月の調査は済んでいるので料金は来月から",
    [RE_MSG_RESEARCH_ALL_HAS] = "%s: 全社購読に含まれている (Ctrl+Shift+クリック: すべてオフ)",
    [RE_MSG_RESEARCH_NO_CASH] = "調査購読: 現金が足りずオンにできない (購読料 %s)",
    [RE_MSG_RESEARCH_BOARD] = "%s: 取締役会の会社なので調査は無料",
    [RE_MSG_HOVER_CHANGE] = "前月比 %+.1f%%",
    [RE_MSG_ROW_CHANGE] = " (前月比 %+.1f%%)",
    [RE_MSG_ROW_CHANGE_FAIR] = " (%+.1f%%、適正 %s)",
    [RE_MSG_HOVER_SUB_OFF] = "Shift+クリック: 調査を購読",
    [RE_MSG_HOVER_SUB_ON] = "調査購読中 (Shift+クリック: オフ)",
    [RE_MSG_HOVER_SUB_ALL] = "調査購読中 (全社)",
    [RE_MSG_HOVER_SUB_BOARD] = "取締役会の会社: 調査無料",
    [RE_MSG_HOVER_ALL_ON] = "Ctrl+Shift+クリック: 全社を購読",
    [RE_MSG_HOVER_ALL_OFF] = "Ctrl+Shift+クリック: すべてオフ",
    [RE_MSG_ROW_SUB_ON] = " (購読中)",
    [RE_MSG_ROW_SUB_BOARD] = " (取締役会: 無料)",
    [RE_MSG_ITEM_FAIR] = "適正 %+.0f%%",
    [RE_MSG_ITEM_SUB] = "購読",
    [RE_MSG_ITEM_BOARD] = "取締役会",
    [RE_MSG_PROPERTY_PREFIX] = "割安な物件: ",
    [RE_MSG_PROPERTY_LINE] = "%s%s、購入手数料を払っても %s の得、価格 %s",
    [RE_MSG_PROPERTY_NONE] = "%s今はなし",
    [RE_MSG_FIT_PREFIX] = "作業効率の低下: ",
    [RE_MSG_FIT_BOTH] = "%s (家具 %.0f%%、資産 %.0f%%)",
    [RE_MSG_FIT_FURNISH] = "%s (家具 %.0f%%)",
    [RE_MSG_FIT_ASSETS] = "%s (資産 %.0f%%)",
    [RE_MSG_FIT_NONE] = "%s (資産が1種類まったく無く、止まっている仕事がある)",
    [RE_MSG_XP_TIP] = "\nMOD: 世帯のメンバーが修了した教育(学位、卒業証書、認定証)は、得た量より下がらない。守るのは、その教育を"
                      "求める仕事・教育・アクティビティのうち最も高い要求値まで。仕事で得た経験は今までどおり毎月減る。",
    [RE_MSG_AUTO_TIP_ALL] = "\nMOD: このスイッチはビジネス全体に効く。誰のものを押しても従業員全員が切り替わる。",
    [RE_MSG_AUTO_TIP_SPARE] = "\nMOD: %dか月続けて、他の従業員の空き時間で済んだ仕事しかしなかった従業員は、退職金なしで解雇する。"
                              "仕事に1人だけで、その間ずっと時間の半分以上が空いていた場合は、勤務時間の少ない候補者がいれば"
                              "その人に替える。",
    [RE_MSG_AUTO_TIP_FILL] = "\nMOD: 今月の作業が従業員の残り時間より多い仕事には、候補者を1人雇う。足りない作業を最も少ない"
                             "お金でこなせる人を選ぶ。",
    [RE_MSG_AUTO_TIP] = "\nMOD: 昇給の要求にはその月の終わり、従業員が辞める直前に答える。その時の候補者に同じ作業をもっと安く"
                        "こなせる人がいればその人に替え、いなければ昇給する。",
    [RE_MSG_ADVERTS_TIP] = "\nMOD: Shift+クリックでこのビジネスの広告をMODに任せる。認知度が%.0f%%未満なら有料広告をすべてオン、"
                           "届いたらオフにする。管理料は月末: 1か月ずっとオンだった広告1つにつき %s。",
    [RE_MSG_ADVERTS_TIP_ON] = "\nMOD: このビジネスの広告はMODが管理中。認知度が%.0f%%未満なら有料広告をすべてオン、届いたらオフに"
                              "する。管理料は月末: 1か月ずっとオンだった広告1つにつき %s。アイコンがオレンジの間は普通のクリックで"
                              "切り替わらない。取り戻すにはShift+クリック。",
    [RE_MSG_ADVERTS_KEPT] = "%s: 広告をMODに任せた",
    [RE_MSG_ADVERTS_BACK] = "%s: 広告を自分で管理する",
    [RE_MSG_ADVERTS_LOCKED] = "%s: この広告はMODが切り替える (取り戻すにはShift+クリック)",
    [RE_MSG_CONTRACTS_KEPT] = "%s: 契約の締結をMODに任せた",
    [RE_MSG_CONTRACTS_BACK] = "%s: 契約の締結を自分で行う",
    [RE_MSG_ALL_KEPT] = "%s: すべてMODに任せた",
    [RE_MSG_ALL_BACK] = "%s: すべて自分で管理する",
    [RE_MSG_ADVERTS_TIP_ALL] = "\nMOD: Ctrl+Shift+クリックでこのビジネス全体をMODに任せ(従業員、資産、広告、契約、フロア"
                               "スペース)、操作をロックする。もう一度で取り戻す。契約だけ任せるなら契約アイコンをShift+クリック。",
    [RE_MSG_CONTRACT_PREFIX] = "MODが結んだ契約: ",
    [RE_MSG_CONTRACT_ITEM] = "%s%s 月%d時間、%dか月、%s",
    [RE_MSG_CONTRACT_FEE] = " (手数料 %s)",
    [RE_MSG_CONTRACT_TICK] = "MODが契約を%d件結んだ",
    [RE_MSG_CONTRACT_ROOM] = "%s: フロアスペースが足りず、今月の契約を結ばなかった",
    [RE_MSG_PREMISES_PREFIX] = "フロアスペース (%s): ",
    [RE_MSG_PREMISES_GROW] = "%s今月末に2倍になり、家賃が月 %s 上がる。スペースが足りないのでMODが星をオンにした",
    [RE_MSG_PREMISES_MOST] = "%s足りないが、この物件はこれ以上広げられない。もっと広い所へ移転が必要",
    [RE_MSG_PREMISES_OWNED] = "%s足りない。所有物件なのでMODは広げなかった。広げるには一度に %s かかる。必要なら自分で星を"
                              "オンにすること",
    [RE_MSG_FIRM_CLOSED] = "%s: 閉店した。再び開くまでMODの自動化は休む(雇用、解雇、資産購入、契約締結をせず、広告はオフ)",
    [RE_MSG_FIRM_OPENED] = "%s: 再び開いた。MODの自動化を続ける",
    [RE_MSG_LOCKED] = "%s: すべてMODに任せたビジネスなのでロック中。自分で操作するには先に広告アイコンをCtrl+Shift+クリックで"
                      "取り戻すこと",
    [RE_MSG_ASSET_BUY_PREFIX] = "不足資産の購入: ",
    [RE_MSG_ASSET_BUY_ITEM] = "%s%s %s %d個",
    [RE_MSG_ASSET_BUY_TOTAL] = " (合計 %s)",
    [RE_MSG_ASSET_SHORT_PREFIX] = "買えなかった資産: ",
    [RE_MSG_ASSET_SHORT_ROOM] = "%s%s %s (スペース不足)",
    [RE_MSG_ASSET_SHORT_CASH] = "%s%s %s (現金不足)",
    [RE_MSG_ASSET_SHORT_NONE] = "%s%s %s (売り物なし)",
    [RE_MSG_ASSET_BUY_DEBT] = " (合計 %s、うち負債 %s)",
    [RE_MSG_ASSET_TICK_BUY] = "不足資産を%d個購入: %s",
    [RE_MSG_ASSET_TICK_DEBT] = " (負債 %s、3か月以内に返済)",
    [RE_MSG_ASSET_REPLACED] = "%s: 新品を購入、%s",
    [RE_MSG_SORT_CHEAP] = "割安順に並べる\n(調査済みのみ)",
    [RE_MSG_SORT_DEAR] = "割高順に並べる\n(調査済みのみ)",
    [RE_MSG_SORT_CHANGE] = "前月比で\n上昇順に並べる",
    [RE_MSG_SORT_CAP] = "時価総額\n大きい順に並べる",
};
